# NOTE: changed dev adapter from async to redis
development:

  adapter: redis

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: thecodebender-api_production
